site_name: py_proj_template
site_url: https://chaitu-ycr.github.io/py_proj_template/
site_description: Enter project description here
site_author: chaitu-ycr

repo_name: chaitu-ycr/py_proj_template
repo_url: https://github.com/chaitu-ycr/py_proj_template.git
edit_uri: blob/main/docs/

nav:
  - about: index.md
  - reference: 999_reference.md

theme:
  name: material
  logo: images/package_logo.png
  features:
    - toc.integrate

plugins:
  - mkdocstrings
  - search

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true